---
title: "Angli Xue's personal website"
author: "[Angli Xue](https://github.com/alexxue81)"
date: "`r format(Sys.time(), '%d %B %Y')`"
mail: "alexxuexue@gmail.com"
linkedin: "angli-xue-1697aa9a"
twitter: "alexxue81"
github: "alexxue81"
#home: "https://sites.google.com/view/angli-xue/home/"
output:
  epuRate::UQ:
    toc: TRUE
    number_sections: FALSE
    code_folding: "hide"
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# You need these libraries to run this template:
library(rmarkdown)    # install.packages("rmarkdown")
library(epuRate)      # devtools::install_github("holtzy/epuRate", force=TRUE)
```

<br><br><br><br>

> Hi! I am Angli Xue, a PhD candidate at [Program in Complex Trait Genomics (PCTG) group](https://cnsgenomics.com/) at University of Queensland, Australia. I am interested in dissecting the genetic architecture of human complex diseases, performing meta-analysis and integrating multi-omics data to identify associated gene loci and gene regulating mechanisms. 

> I'm currently working at [Prof. Jian Yang](https://scholar.google.com.au/citations?user=aLuqQs8AAAAJ&hl=en)'s laboratory, and my PhD thesis topic is "identification of genetic and modifiable risk factors for complex traits and diseases".


# Overview
***
Angli Xue is a PhD student at [Institute for Molecular Bioscience](https://imb.uq.edu.au/) (IMB), The [University of Queensland](https://www.uq.edu.au/) (UQ). He received his bachelor in 2015 from [Zhejiang University](http://www.zju.edu.cn/english/) (ZJU), China, which was followed by a one-year research assistant at the [Institute of Bioinformatics](http://ibi.zju.edu.cn/), ZJU. He joined [Program in Complex Trait Genomics](https://cnsgenomics.com/) (PCTG) group at UQ in 2016. His research interests are in dissecting the genetic architecture of human complex diseases, performing meta-analysis and integrating multi-omics data to identify associated gene loci and gene regulating mechanisms.


# Research focuses
***
- Genetic architecture of complex traits and diseases (e.g. type 2 diabetes, skin cancer, substance use, Parkinson's disease)

- Integrative analyses of multi-omics data (e.g. SNP, gene expression, DNA methylation and histone modification)

- Genetic correlation among substance and behavioural addiction (e.g. smoking, alcohol consumption and cannabis use)

- Causal association between addictive behaviours/physical activities and common diseases/socio-economic status

- X chromosome inactivation (e.g. dosage compensation model)


# Qualifications
***
- PhD in Statistical Genetics, The University of Queensland, 2016 - 2021

- Bachelor in Agronomy, Zhejiang University, 2011 - 2015

# Selected Publications
***
[Genome-wide association analyses identify 143 risk variants and putative regulatory mechanisms for type 2 diabetes](https://www.nature.com/articles/s41467-018-04951-w)

Angli Xue, Yang Wu, Zhihong Zhu, Futao Zhang, Kathryn E Kemper, Zhili Zheng, Loic Yengo, Luke R. Lloyd-Jones, Julia Sidorenko, Yeda Wu, eQTLGen Consortium, Allan F McRae, Peter M Visscher, Jian Zeng, Jian Yang. Genome-wide association analyses identify 143 risk variants and putative regulatory mechanisms for type 2 diabetes. Nature Communications. 2018. 9 (1), 1-14.

[Dissecting genetic architecture of complex trait using multi-omics information: A case of association mapping for startle response in Drosophila melanogaster](https://www.nature.com/articles/s41598-017-11676-1)

Angli Xue, Hongcheng Wang, Jun Zhu. Dissecting genetic architecture of complex trait using multi-omics information: A case of association mapping for startle response in Drosophila melanogaster. Scientific Reports. 2017. 7 (1), 1-7.

## Preprint
[Genome-wide analyses of behavioural traits biased by misreports and longitudinal changes](https://www.medrxiv.org/content/10.1101/2020.06.15.20131284v1)

Angli Xue, Longda Jiang, Zhihong Zhu, Naomi R. Wray, Peter M. Visscher, Jian Zeng, Jian Yang. Genome-wide analyses of behavioural traits biased by misreports and longitudinal changes. Under review. 2020.

[Bayesian analysis of summary data reveals differential signatures of natural selection across human complex traits and functional genomic regions](https://www.biorxiv.org/content/10.1101/752527v1)

Jian Zeng, Angli Xue, Longda Jiang, Luke R Lloyd-Jones, Yang Wu, Huanwei Wang, Zhili Zheng, Loic Yengo, Kathryn E Kemper, Naomi R Wray, Peter M Visscher, Jian Yang. Bayesian analysis of summary data reveals differential signatures of natural selection across human complex traits and functional genomic regions. Under review. 2020.



# More
***
Read more about my publications [Google scholar](https://scholar.google.com.au/citations?user=pKYOAm0AAAAJ&hl=en).

Learn about my peer review activity [Publons](https://publons.com/researcher/1390585/angli-xue/).